[project]
name = "brooks_xpeel_module"
version = "1.1.0"
description = "Software for automatting a A4S sealer device"
authors = [
    {name = "Doga Ozgulbas", email="dozgulbas@anl.gov"},
    {name = "Ryan D. Lewis", email="ryan.lewis@anl.gov"},
    {name = "Tobias Ginsburg", email = "tginsburg@anl.gov"},
]
dependencies = [
    "pyserial",
    "madsci.node_module~=0.8.0",
    "madsci.client~=0.8.0",
    "madsci.common~=0.8.0",
]

requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/AD-SDL/brooks_xpeel_module"

######################
# Build Info + Tools #
######################
[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
    "ruff>=0.11.7",
    "pytest",
]
